//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""CombatP1"",
            ""id"": ""051ef5b3-cd82-4111-8118-1552deaed5ea"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""c1fd1992-94ab-4da0-acc4-6ab0e3761756"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack 1"",
                    ""type"": ""Button"",
                    ""id"": ""21364004-2469-4dfd-a577-59a98c0d56cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack 2"",
                    ""type"": ""Button"",
                    ""id"": ""44478c3d-0141-4893-ac7e-3e26ec879a2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack 3"",
                    ""type"": ""Button"",
                    ""id"": ""c418a08d-0152-40c9-abb1-007d2e216d81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick Step Forward"",
                    ""type"": ""Button"",
                    ""id"": ""98ae4dc9-2607-4e07-bf28-1694e62488ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick Step Back"",
                    ""type"": ""Button"",
                    ""id"": ""d08b5280-2bd0-4474-a2aa-7336866594a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slam"",
                    ""type"": ""Button"",
                    ""id"": ""d6eff31d-719a-49d8-b5b9-b36de1015981"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate Page Forward"",
                    ""type"": ""Button"",
                    ""id"": ""92487e57-aa0d-4771-ab7b-a7667fdbd1ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate Page Backward"",
                    ""type"": ""Button"",
                    ""id"": ""7f1d19d7-0b0e-4c0f-9868-df8c5487a8b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Counter 1"",
                    ""type"": ""Button"",
                    ""id"": ""59190abd-da9d-4565-9621-c4d9b4aced13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Counter 2"",
                    ""type"": ""Button"",
                    ""id"": ""c2a8010f-5f20-4811-bc24-327158fd3cae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Counter 3"",
                    ""type"": ""Button"",
                    ""id"": ""54857634-3706-47ee-8b27-8e230a880b3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c9c6faf5-49bb-4d00-9d6e-13f29da8f0e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Left/Right Movement"",
                    ""id"": ""b2a75d6c-d27b-46d1-b4bd-4693c9b35ee2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""aa7117cc-4aca-47a5-9207-5522cca2977e"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""e9600e2b-ef36-4b48-bc50-6561c02ab4d7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""c69f6dad-09ed-43fd-9695-835bc301d2a7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""b4869dde-ab41-4376-bff6-badffcab195b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b506d541-0573-49b6-9996-0ae2895fd043"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Attack 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90bbea98-e635-4588-b9ca-55b04e99d687"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Attack 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd1bd781-6905-4c72-a7c7-c54b387920cd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Attack 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""8166169d-9405-4147-bc70-257b056cc3e0"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick Step Forward"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f6d601df-7f6f-4171-b260-343cfa2540b0"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Quick Step Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""ad663cfe-5897-495e-bdb7-40c43b0a6090"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Quick Step Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""f85ec69f-703c-4b32-be05-72975102ed28"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Quick Step Back"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""661605ca-477e-4c37-8df4-4e9185731fd2"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Quick Step Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""4275a3ce-0200-4dac-975b-917229641292"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Quick Step Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cff97a30-8aa6-4b04-b0c7-70ab59c12382"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Slam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d077a95-78a7-4694-8c15-8b4665c23395"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Rotate Page Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4014dfe0-3571-4297-ba3c-8e4dd50151a9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Rotate Page Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""9ed77387-eacc-4713-a3c0-6a33c3e9daa1"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Counter 1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""807e0e14-1473-4d92-9029-30bd0206bc97"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""fb4df66f-b5c0-43fc-b47c-862b0d640a82"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""a642f79d-4d77-4c93-be2e-ae5de9de3e7c"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3fe8aeae-e9f5-417d-bfc8-4d509c12457c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""326e2afa-7787-4459-a2d3-1b657ac7439f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""80f691ad-21f3-4777-9d64-468c0669a2cb"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c245826d-b5fe-44d0-95d0-5e025819f945"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""bfaeb429-a8c6-4257-9712-4af7c329da26"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Counter 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6f98c17c-d578-4aef-b591-adb3f1d981b1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Game Control Scheme"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Game Control Scheme"",
            ""bindingGroup"": ""Game Control Scheme"",
            ""devices"": []
        }
    ]
}");
        // CombatP1
        m_CombatP1 = asset.FindActionMap("CombatP1", throwIfNotFound: true);
        m_CombatP1_Movement = m_CombatP1.FindAction("Movement", throwIfNotFound: true);
        m_CombatP1_Attack1 = m_CombatP1.FindAction("Attack 1", throwIfNotFound: true);
        m_CombatP1_Attack2 = m_CombatP1.FindAction("Attack 2", throwIfNotFound: true);
        m_CombatP1_Attack3 = m_CombatP1.FindAction("Attack 3", throwIfNotFound: true);
        m_CombatP1_QuickStepForward = m_CombatP1.FindAction("Quick Step Forward", throwIfNotFound: true);
        m_CombatP1_QuickStepBack = m_CombatP1.FindAction("Quick Step Back", throwIfNotFound: true);
        m_CombatP1_Slam = m_CombatP1.FindAction("Slam", throwIfNotFound: true);
        m_CombatP1_RotatePageForward = m_CombatP1.FindAction("Rotate Page Forward", throwIfNotFound: true);
        m_CombatP1_RotatePageBackward = m_CombatP1.FindAction("Rotate Page Backward", throwIfNotFound: true);
        m_CombatP1_Counter1 = m_CombatP1.FindAction("Counter 1", throwIfNotFound: true);
        m_CombatP1_Counter2 = m_CombatP1.FindAction("Counter 2", throwIfNotFound: true);
        m_CombatP1_Counter3 = m_CombatP1.FindAction("Counter 3", throwIfNotFound: true);
        m_CombatP1_Pause = m_CombatP1.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CombatP1
    private readonly InputActionMap m_CombatP1;
    private ICombatP1Actions m_CombatP1ActionsCallbackInterface;
    private readonly InputAction m_CombatP1_Movement;
    private readonly InputAction m_CombatP1_Attack1;
    private readonly InputAction m_CombatP1_Attack2;
    private readonly InputAction m_CombatP1_Attack3;
    private readonly InputAction m_CombatP1_QuickStepForward;
    private readonly InputAction m_CombatP1_QuickStepBack;
    private readonly InputAction m_CombatP1_Slam;
    private readonly InputAction m_CombatP1_RotatePageForward;
    private readonly InputAction m_CombatP1_RotatePageBackward;
    private readonly InputAction m_CombatP1_Counter1;
    private readonly InputAction m_CombatP1_Counter2;
    private readonly InputAction m_CombatP1_Counter3;
    private readonly InputAction m_CombatP1_Pause;
    public struct CombatP1Actions
    {
        private @PlayerControls m_Wrapper;
        public CombatP1Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CombatP1_Movement;
        public InputAction @Attack1 => m_Wrapper.m_CombatP1_Attack1;
        public InputAction @Attack2 => m_Wrapper.m_CombatP1_Attack2;
        public InputAction @Attack3 => m_Wrapper.m_CombatP1_Attack3;
        public InputAction @QuickStepForward => m_Wrapper.m_CombatP1_QuickStepForward;
        public InputAction @QuickStepBack => m_Wrapper.m_CombatP1_QuickStepBack;
        public InputAction @Slam => m_Wrapper.m_CombatP1_Slam;
        public InputAction @RotatePageForward => m_Wrapper.m_CombatP1_RotatePageForward;
        public InputAction @RotatePageBackward => m_Wrapper.m_CombatP1_RotatePageBackward;
        public InputAction @Counter1 => m_Wrapper.m_CombatP1_Counter1;
        public InputAction @Counter2 => m_Wrapper.m_CombatP1_Counter2;
        public InputAction @Counter3 => m_Wrapper.m_CombatP1_Counter3;
        public InputAction @Pause => m_Wrapper.m_CombatP1_Pause;
        public InputActionMap Get() { return m_Wrapper.m_CombatP1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CombatP1Actions set) { return set.Get(); }
        public void SetCallbacks(ICombatP1Actions instance)
        {
            if (m_Wrapper.m_CombatP1ActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnMovement;
                @Attack1.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack1;
                @Attack1.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack1;
                @Attack1.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack1;
                @Attack2.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack2;
                @Attack2.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack2;
                @Attack2.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack2;
                @Attack3.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack3;
                @Attack3.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack3;
                @Attack3.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnAttack3;
                @QuickStepForward.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnQuickStepForward;
                @QuickStepForward.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnQuickStepForward;
                @QuickStepForward.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnQuickStepForward;
                @QuickStepBack.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnQuickStepBack;
                @QuickStepBack.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnQuickStepBack;
                @QuickStepBack.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnQuickStepBack;
                @Slam.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnSlam;
                @Slam.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnSlam;
                @Slam.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnSlam;
                @RotatePageForward.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnRotatePageForward;
                @RotatePageForward.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnRotatePageForward;
                @RotatePageForward.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnRotatePageForward;
                @RotatePageBackward.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnRotatePageBackward;
                @RotatePageBackward.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnRotatePageBackward;
                @RotatePageBackward.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnRotatePageBackward;
                @Counter1.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter1;
                @Counter1.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter1;
                @Counter1.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter1;
                @Counter2.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter2;
                @Counter2.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter2;
                @Counter2.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter2;
                @Counter3.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter3;
                @Counter3.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter3;
                @Counter3.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnCounter3;
                @Pause.started -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_CombatP1ActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_CombatP1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Attack1.started += instance.OnAttack1;
                @Attack1.performed += instance.OnAttack1;
                @Attack1.canceled += instance.OnAttack1;
                @Attack2.started += instance.OnAttack2;
                @Attack2.performed += instance.OnAttack2;
                @Attack2.canceled += instance.OnAttack2;
                @Attack3.started += instance.OnAttack3;
                @Attack3.performed += instance.OnAttack3;
                @Attack3.canceled += instance.OnAttack3;
                @QuickStepForward.started += instance.OnQuickStepForward;
                @QuickStepForward.performed += instance.OnQuickStepForward;
                @QuickStepForward.canceled += instance.OnQuickStepForward;
                @QuickStepBack.started += instance.OnQuickStepBack;
                @QuickStepBack.performed += instance.OnQuickStepBack;
                @QuickStepBack.canceled += instance.OnQuickStepBack;
                @Slam.started += instance.OnSlam;
                @Slam.performed += instance.OnSlam;
                @Slam.canceled += instance.OnSlam;
                @RotatePageForward.started += instance.OnRotatePageForward;
                @RotatePageForward.performed += instance.OnRotatePageForward;
                @RotatePageForward.canceled += instance.OnRotatePageForward;
                @RotatePageBackward.started += instance.OnRotatePageBackward;
                @RotatePageBackward.performed += instance.OnRotatePageBackward;
                @RotatePageBackward.canceled += instance.OnRotatePageBackward;
                @Counter1.started += instance.OnCounter1;
                @Counter1.performed += instance.OnCounter1;
                @Counter1.canceled += instance.OnCounter1;
                @Counter2.started += instance.OnCounter2;
                @Counter2.performed += instance.OnCounter2;
                @Counter2.canceled += instance.OnCounter2;
                @Counter3.started += instance.OnCounter3;
                @Counter3.performed += instance.OnCounter3;
                @Counter3.canceled += instance.OnCounter3;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public CombatP1Actions @CombatP1 => new CombatP1Actions(this);
    private int m_GameControlSchemeSchemeIndex = -1;
    public InputControlScheme GameControlSchemeScheme
    {
        get
        {
            if (m_GameControlSchemeSchemeIndex == -1) m_GameControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Game Control Scheme");
            return asset.controlSchemes[m_GameControlSchemeSchemeIndex];
        }
    }
    public interface ICombatP1Actions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnAttack1(InputAction.CallbackContext context);
        void OnAttack2(InputAction.CallbackContext context);
        void OnAttack3(InputAction.CallbackContext context);
        void OnQuickStepForward(InputAction.CallbackContext context);
        void OnQuickStepBack(InputAction.CallbackContext context);
        void OnSlam(InputAction.CallbackContext context);
        void OnRotatePageForward(InputAction.CallbackContext context);
        void OnRotatePageBackward(InputAction.CallbackContext context);
        void OnCounter1(InputAction.CallbackContext context);
        void OnCounter2(InputAction.CallbackContext context);
        void OnCounter3(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
